// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcxZxHpm7s9Rw4oHR0-YesJGZpuNOcsAQ',
    appId: '1:1015825053135:web:98b6c60771f08aeeb30eba',
    messagingSenderId: '1015825053135',
    projectId: 'taski-98d49',
    authDomain: 'taski-98d49.firebaseapp.com',
    storageBucket: 'taski-98d49.firebasestorage.app',
    measurementId: 'G-KJ2HK52SES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNsFAVP0cCmdXPTpZ5mQCTNzsWEBdsDw',
    appId: '1:1015825053135:android:30d7a85c340269b1b30eba',
    messagingSenderId: '1015825053135',
    projectId: 'taski-98d49',
    storageBucket: 'taski-98d49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wcEKz95Pyebm5uesueqYkOWZ7Qr5vdg',
    appId: '1:1015825053135:ios:0e2079239ea2ca20b30eba',
    messagingSenderId: '1015825053135',
    projectId: 'taski-98d49',
    storageBucket: 'taski-98d49.firebasestorage.app',
    iosBundleId: 'com.example.taskiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wcEKz95Pyebm5uesueqYkOWZ7Qr5vdg',
    appId: '1:1015825053135:ios:0e2079239ea2ca20b30eba',
    messagingSenderId: '1015825053135',
    projectId: 'taski-98d49',
    storageBucket: 'taski-98d49.firebasestorage.app',
    iosBundleId: 'com.example.taskiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcxZxHpm7s9Rw4oHR0-YesJGZpuNOcsAQ',
    appId: '1:1015825053135:web:50adf22220709dd5b30eba',
    messagingSenderId: '1015825053135',
    projectId: 'taski-98d49',
    authDomain: 'taski-98d49.firebaseapp.com',
    storageBucket: 'taski-98d49.firebasestorage.app',
    measurementId: 'G-GH8KW5D81L',
  );
}
